package main.java.data_access;

import main.java.use_case.go_to_personal_profile.GoToPersonalProfileDataAccessInterface;

public class GoToPersonalProfileViewDataAccessObject implements GoToPersonalProfileDataAccessInterface {
}
